# Each error message must (at least) contain this kind of line :
# Error line [line]: [message].
# ex : Error line 3: Wrong number of parameters for this intruction.
# This line will be compared. Give the error type and the line of the error in INPUT.

ERROR_TYPE = {
	# "PARAM_NB":			"Wrong number of parameters for this intruction."
	
	"NO_NAME":				"Name was expected in the source file.",
	"NO_COMMENT":			"Comment was expected in the source file.",
	"BAD_QUOTES":			"Bad quoting.",
	"BIG_NAME":				"Name is too long.",
	"BIG_COMMENT":			"Comment is too long.",
	"INVALID_CHAR":			"Invalid character.",
	"EXPECT_LABEL":			"Label name was expected.",
	"INVALID_PARAM":		"Invalid parameter."
}

INPUT = {
	# "zork.s":	{"error": False, "error_type": None, "error_line": -1},
	"name.none.s":	{"error": True,  "error_type": "NO_NAME", "error_line": 1},
	"name.too_long.s":	{"error": True,  "error_type": "BIG_NAME", "error_line": 1},
	"name.bad_quoting.s":	{"error": True,  "error_type": "BAD_QUOTES", "error_line": 1},
	"name.bad_quoting.1.s":	{"error": True,  "error_type": "BAD_QUOTES", "error_line": 1},
	"name.bad_quoting.2.s":	{"error": True,  "error_type": "BAD_QUOTES", "error_line": 1},
	"name.instr_before.s":	{"error": True,  "error_type": "NO_NAME", "error_line": 3},
	"comment.none.s":	{"error": True,  "error_type": "NO_COMMENT", "error_line": 3},
	"comment.too_long.s":	{"error": True,  "error_type": "BIG_COMMENT", "error_line": 2},
	"comment.bad_quoting.s":	{"error": True,  "error_type": "BAD_QUOTES", "error_line": 2},
	"comment.bad_quoting.1.s":	{"error": True,  "error_type": "BAD_QUOTES", "error_line": 2},
	"comment.bad_quoting.2.s":	{"error": True,  "error_type": "BAD_QUOTES", "error_line": 2},
	"comment.instr_before.s":	{"error": True,  "error_type": "NO_COMMENT", "error_line": 2},
	"lexer.bad_char.s":	{"error": True,  "error_type": "INVALID_CHAR", "error_line": 4},
	"lexer.empty.s":	{"error": False,  "error_type": None, "error_line": -1},
	"parser.label.no_str.s":	{"error": True,  "error_type": "EXPECT_LABEL", "error_line": 3},
	"coco.s":	{"error": False,  "error_type": None, "error_line": -1},
	"42.s":	{"error": True,  "error_type": "INVALID_PARAM", "error_line": 212},
	"Asombra.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "Backward.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Car.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "Death.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Douceur_power.s":	{"error": True,  "error_type": "INVALID_PARAM", "error_line": 13},
	"Explosive_Kitty.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Gagnant.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Kappa.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Kittystrophic.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Machine-gun.s":	{"error": False,  "error_type": None, "error_line": -1},
	"MarineKing.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Misaka_Mikoto.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Octobre_Rouge_V4.2.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Rainbow_dash.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "Survivor.s":	{"error": False,  "error_type": None, "error_line": -1},
	"THUNDER.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "Torpille.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Varimathras.s":	{"error": False,  "error_type": None, "error_line": -1},
	"Wall.s":	{"error": False,  "error_type": None, "error_line": -1},
	"_.s":	{"error": False,  "error_type": None, "error_line": -1},
	"_honeybadger.s":	{"error": False,  "error_type": None, "error_line": -1},
	"barriere.s":	{"error": False,  "error_type": None, "error_line": -1},
	"bee_gees.s":	{"error": False,  "error_type": None, "error_line": -1},
	"big_feet.s":	{"error": False,  "error_type": None, "error_line": -1},
	"bigzork.s":	{"error": False,  "error_type": None, "error_line": -1},
	"casimir.s":	{"error": False,  "error_type": None, "error_line": -1},
	"champ.s":	{"error": False,  "error_type": None, "error_line": -1},
	"corelol.s":	{"error": False,  "error_type": None, "error_line": -1},
	"darksasuke.s":	{"error": False,  "error_type": None, "error_line": -1},
	"doge.s":	{"error": False,  "error_type": None, "error_line": -1},
	"dubo.s":	{"error": False,  "error_type": None, "error_line": -1},
	"ex.s":	{"error": False,  "error_type": None, "error_line": -1},
	"file.s":	{"error": False,  "error_type": None, "error_line": -1},
	"fluttershy.s":	{"error": False,  "error_type": None, "error_line": -1},
	"gateau.s":	{"error": False,  "error_type": None, "error_line": -1},
	"gedeon.s":	{"error": False,  "error_type": None, "error_line": -1},
	"helltrain.s":	{"error": False,  "error_type": None, "error_line": -1},
	"jinx.s":	{"error": False,  "error_type": None, "error_line": -1},
	"jumper.s":	{"error": False,  "error_type": None, "error_line": -1},
	"justin_bee.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "lde.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "leeloo.s":	{"error": False,  "error_type": None, "error_line": -1},
	"littlepuppy.s":	{"error": False,  "error_type": None, "error_line": -1},
	"live.s":	{"error": False,  "error_type": None, "error_line": -1},
	"loose.s":	{"error": False,  "error_type": None, "error_line": -1},
	"mandragore.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "mat.s":	{"error": False,  "error_type": None, "error_line": -1},
	"maxidef.s":	{"error": False,  "error_type": None, "error_line": -1},
	"meowluigi.s":	{"error": False,  "error_type": None, "error_line": -1},
	"mise_a_jour_windows95.s":	{"error": False,  "error_type": None, "error_line": -1},
	"mortel.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "new.s":	{"error": False,  "error_type": None, "error_line": -1},
	"overwatch.s":	{"error": False,  "error_type": None, "error_line": -1},
	"perm_denied.s":	{"error": False,  "error_type": None, "error_line": -1},
	"results.s":	{"error": False,  "error_type": None, "error_line": -1},
	"run_Kitty_RUN.s":	{"error": False,  "error_type": None, "error_line": -1},
	"salamahenagalabadoun.s":	{"error": False,  "error_type": None, "error_line": -1},
	"sam_2.0.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "sebc.s":	{"error": False,  "error_type": None, "error_line": -1},
	"skynet.s":	{"error": False,  "error_type": None, "error_line": -1},
	"slider2.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "tdc2.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "tdc3.s":	{"error": False,  "error_type": None, "error_line": -1},
	# "tdc4.s":	{"error": False,  "error_type": None, "error_line": -1},
	"terminator.s":	{"error": False,  "error_type": None, "error_line": -1},
	"toto.s":	{"error": False,  "error_type": None, "error_line": -1},
	"turtle.s":	{"error": False,  "error_type": None, "error_line": -1},
	"ultima.s":	{"error": False,  "error_type": None, "error_line": -1},
	"ultimate-surrender.s":	{"error": False,  "error_type": None, "error_line": -1},
	"youforkmytralala.s":	{"error": False,  "error_type": None, "error_line": -1},
	"zork.s":	{"error": False,  "error_type": None, "error_line": -1}
}
