version: 2
jobs:
  build:
    docker:
      - image: gcc:8
    working_directory: ~/corewar
    steps:
      - checkout
      - run:
          name: Current Time
          command: date
      - run:
          name: ASM Compilation
          command: make
      - persist_to_workspace:
          root: .
          paths:
            - asm/asm
  test:
    docker:
      - image: circleci/python:3.7.1-stretch
    working_directory: ~/corewar
    steps:
      - checkout
      - attach_workspace:
          at: ~/corewar
      - run:
          name: ls
          command: ls -la asm
      - run:
          name: Run tests
          command: python3 asm/tests/main.py

workflows:
  version: 2
  build_and_test:
    filters:
      branches:
        only:
          - master
          - asm
    jobs:
      - build
      - test:
          requires:
            - build
