version: 2
jobs:
  build:
    docker:
      - image: gcc:8
    working_directory: ~/corewar
    steps:
      - checkout
      - run:
          name: Current Time
          command: date
      - run:
          name: ASM Compilation
          command: make
  test:
    docker:
      - image: circleci/python:3.7.1-stretch
    working_directory: ~/corewar
    steps:
      - checkout
      - run:
          name: ls
          command: ls -la asm
      - run:
          name: Run tests
          command: python3 asm/tests/main.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
