version: 2
jobs:
  build:
    docker:
      - image: gcc:8
    working_directory: ~/corewar
    steps:
      - checkout
      - run:
          name: Current Time
          command: date
      - run:
          name: ASM Compilation
          command: make
      - persist_to_workspace:
          root: .
          paths:
            - asm/asm
            - vm/corewar
  test:
    docker:
      - image: circleci/python:3.7.1-stretch
    working_directory: ~/corewar
    steps:
      - checkout
      - attach_workspace:
          at: ~/corewar
      - run:
          name: check asm repo
          command: ls -la asm
      - run:
          name: check vm repo
          command: ls -la vm
      - run:
          name: Run tests
          command: make run_tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
